version: '3.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports: 
      - 6901:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: builditlearn
      MYSQL_USER: user
      MYSQL_PASSWORD: user

  pma:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 6902:80
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      PMA_HOST: mysql